CREATE ROLE aux_app LOGIN PASSWORD 'aux-app-development-secret' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE aux_worker LOGIN PASSWORD 'aux-worker-development-secret' NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS;
GRANT CONNECT ON DATABASE aux TO aux_app, aux_worker;
GRANT USAGE ON SCHEMA public TO aux_app, aux_worker;
ALTER DEFAULT PRIVILEGES FOR ROLE aux IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aux_app, aux_worker;
ALTER DEFAULT PRIVILEGES FOR ROLE aux IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO aux_app, aux_worker;
